// AUTO-GENERATED by scripts/generate-favicon.mjs — do not edit by hand.
// Re-run `node scripts/generate-favicon.mjs` to regenerate this and the favicon set.
'use client';

import { useId } from 'react';

export interface LogoProps {
  /** Rendered size in px. Default 28. */
  size?: number;
  className?: string;
  /** Set false to drop the outer rim (useful on very small renders). */
  rim?: boolean;
  /**
   * Corner radius in viewBox units (the tile is 100x100), default 22.
   * A Tailwind rounded-* class cannot square off the tile, because the
   * corners belong to the SVG's own <rect> rather than the element box.
   */
  radius?: number;
}

/**
 * The MBA Planner mark: a geometric "M" monogram on a rounded tile.
 *
 * Tint it per-theme with CSS custom properties:
 *   --logo-tile, --logo-mark-from, --logo-mark-to
 */
export function Logo({ size = 28, className, rim = true, radius = 22 }: LogoProps) {
  // Gradient ids must be unique per instance or multiple logos on one page
  // will all resolve to whichever <defs> rendered first.
  const uid = useId().replace(/:/g, '');

  return (
    <svg
      viewBox="0 0 100 100"
      width={size}
      height={size}
      className={className}
      role="img"
      aria-label="MBA Planner"
    >
      <defs>
        <linearGradient id={`m${uid}`} x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stopColor="var(--logo-mark-from, #FBBF24)" />
          <stop offset="1" stopColor="var(--logo-mark-to, #F59E0B)" />
        </linearGradient>
      </defs>
      <rect width="100" height="100" rx={radius} fill="var(--logo-tile, #0F172A)" />
      {rim && (
        <rect
          x="1.25"
          y="1.25"
          width="97.5"
          height="97.5"
          rx={Math.max(radius - 1.25, 0)}
          fill="none"
          stroke="var(--logo-mark-to, #F59E0B)"
          strokeWidth="2.5"
          opacity="0.55"
        />
      )}
      <path d="M 21 74 L 21 26 L 40 26 L 50 63 L 60 26 L 79 26 L 79 74 L 60 74 L 60 45.53 L 50 72.5 L 40 45.53 L 40 74 Z" fill={`url(#m${uid})`} />
    </svg>
  );
}

export default Logo;
