// Returns the chatbot's opening greeting. Deterministic (no model call) — a short rotation of
// warm, course-agnostic lines themed around "which course would you like help with?". This used
// to be generated by the model on every chat-open; that was a per-open API cost for a one-line
// greeting, so it now comes from a static rotation instead.

import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';

const GREETINGS = [
  'Hey! Which of your courses would you like my help with?',
  'Hi there — pick a course below and I’ll tell you whatever you need to know.',
  'Hello! Which course can I help you get a handle on today?',
  'Hey! Tap a course below, or just ask me anything about this term.',
];

function randomGreeting(): string {
  return GREETINGS[Math.floor(Math.random() * GREETINGS.length)];
}

export async function POST() {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) {
    return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });
  }

  return NextResponse.json({ greeting: randomGreeting() });
}
